# Generated by Django 2.2.4 on 2019-08-25 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts_people',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Home'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('work', 'Work'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('contact_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phone_number', to='contact.Contact')),
            ],
            options={
                'db_table': 'contacts_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=10)),
                ('email_address', models.EmailField(db_index=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('contact_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_email_address', to='contact.Contact')),
            ],
            options={
                'db_table': 'contacts_email_addresses',
                'unique_together': {('contact_object', 'email_address')},
            },
        ),
    ]
